CREATE TABLE PLAYER
(
PLAYER_ID   INTEGER   PRIMARY KEY,
PLAYER_NAME VARCHAR2  (100) NOT NULL,
TEAM_ID     VARCHAR2  (20)      NULL,
WINRATE     VARCHAR2  (3)       NULL
);

CREATE TABLE TEAM_ID
TEAM_ID NUMBER  NOT NULL,
TEAM_NAME VARCHAR2 NOT NULL,
MEMBER NULL,
CAREER NULL
);


